server:
  port: 8002

mybatis:
  mapper-locations:
  - classpath:mapper/**/*.xml

spring:
  application:
    name: spring-cloud-practise-prod-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db_demo_2
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: spring-cloud-practise-prod-provider-8002
    prefer-ip-address: true
